//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollegeManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grade
    {
        public int GradeId { get; set; }
        public int GradeDescription { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public int CourseId { get; set; }
    
        public virtual Course Course { get; set; }
        public virtual Student Student { get; set; }
        public virtual Subject Subject { get; set; }
    }
}
